swagger: "2.0"
definitions:
  routeTableSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - routeTableName
    properties:
      vpcId:
        type: string
        description: Virtual private cloud ID of route table
      routeTableName:
        type: string
        description: Route table name, only allowed to enter Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters.
      description:
        type: string
        description: Description, all characters allowed to enter under UTF-8 coding, which is not exceed 256 characters
