swagger: "2.0"
definitions:
  segment:
    x-jdcloud-module: vpc
    properties:
      segmentId:
        type: string
        description: Segment Id
      segmentName:
        type: string
        description: Segment name, only allowed to enter Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters.
      description:
        type: string
        description: Segment description, all characters allowed to enter under UTF-8 coding, which is not exceed 256 characters.
      addressPrefix:
        type: string
        description: Network address field
      availableIpCount:
        type: integer
        description: Number of available IPs in segment
      provider:
        type: string
        description: IP service provider, values include bgp or no_bgp, cn-north-1: bgp; cn-south-1: [bgp, no_bgp]; cn-east-1: [bgp, no_bgp]; cn-east-2: bgp
      startIp:
        type: string
        description: Segment start address
      endIp:
        type: string
        description: Segment end address


