swagger: "2.0"
definitions:
  createAlarmBody:
    ###################### Create alarm ######################
    x-jdcloud-module: monitor
    type: object
    required:
    - clientToken
    - createAlarmSpec
    properties:
      clientToken:
        description: Idempotent validation parameter, 32-bit at the longest, the return value will not change if the value does not change
        type: string
      createAlarmSpec:
          $ref: '#/definitions/CreateAlarmSpec'
  CreateAlarmSpec:
    x-jdcloud-module: monitor
    description: Create monitoring rules
    type: object
    required:
      - serviceCode
      - metric
      - resourceIds
      - period
      - calculation
      - operation
      - threshold
      - times
    properties:
      calculation:
        description: Statistical method must be consistent with the defined metric, with an optional list of values: avg, max, sum, min
        type: string
      contactGroups:
        description: Contact group notified by alarm rules must be already created on the console, for example“[‘contact group 1’, ‘contact group 2’]”
        type: array
        items:
          type: string
      contactPersons:
        description: Contacts notified by alarm rules must be already created on the console, for example“[‘contact 1’, ‘contact 2’]”
        type: array
        items:
          type: string
      downSample:
        description: Sampling frequency, some metrics support setting downSample, through <a href=”https://www.jdcloud.com/help/detail/2791/isCatalog/1”>[Query indicator list of available creating monitoring rules]</a>Interface is available for viewing.
        type: string
      metric:
        description: Please view <a href="https://www.jdcloud.com/help/detail/2791/isCatalog/1”> for values[Query indicator list of available creating monitoring rules]]</a> metric field of interface
        type: string
      noticePeriod:
        description: Notification period unit: hour
        type: integer
      operation:
        description: 报警比较符，只能为以下几种<=,<,>,>=,==,!=
        type: string
      period:
        description: Statistical period, unit in minutes, currently supported value: 2, 5, 15, 30, 60
        type: integer
      resourceIds:
        description: Alarm rules shall correspond to the Instance List, 100 pieces at most each time, for example"['resourceId1','resourceId2']"
        type: array
        items:
          type: string
      serviceCode:
        description: Product name, please view <a href="https://www.jdcloud.com/help/detail/2791/isCatalog/1”> for values[Query indicator list of available creating monitoring rules]]</a> serviceCode field of interface
        type: string
      threshold:
        description: Alarm threshold, currently, only numeric type functions are available
        type: number
        format: double
      times:
        description: Continuous periods, alarms are made when several statical periods meet threshold value conditions through continuous detections, optional values: 1, 2, 3, 5
        type: integer

  updateAlarmBody:
    ###################### Modify alarm######################  
    x-jdcloud-module: monitor
    type: object
    required:
      - serviceCode
      - metric
      - period
      - calculation
      - operation
      - threshold
      - times
    properties:
      calculation:
        description: Statistical method: average value=avg, maximum value=max, minimum value=min, summation=sum
        type: string
      contactGroups:
        description: Contact group notified, for example [“contact group 1”, “contact group 2”]
        type: array
        items:
          type: string
      contactPersons:
        description: Contact notified, for example“[‘contact 1’, ‘contact 2’]”
        type: array
        items:
          type: string
      downSample:
        description: Sampling frequency
        type: string
      metric:
        description: Query Metric field returned by list interface of available monitoring item based on the product line
        type: string
      noticePeriod:
        description: Notification period unit: hour
        type: integer
      operation:
        description: '>=、>、<、<=、==、!='
        type: string
      period:
        description: Statistical period (unit: minute), optional value: 2, 5, 15, 30, 60
        type: integer
      serviceCode:
        description: Product name
        type: string
      threshold:
        description: Threshold
        type: number
        format: double
      times:
        description: Alarm after how many times, optional value: 1, 2, 3, 5
        type: integer

  alarmHistory:
    ###################### Alarm history######################  
    x-jdcloud-module: monitor
    type: object
    properties:
      calculation:
        description: Statistical method: average value=avg, maximum value=max, minimum value=min,
        type: string
      contactGroups:
        description: Contact group notified, for example [“contact group 1”, “contact group 2”]
        type: array
        items:
          type: string
      contactPersons:
        description: Contact notified, for example“[‘contact 1’, ‘contact 2’]”
        type: array
        items:
          type: string
      deleted:
        description: Whether the rule has been deleted, 1 represents it has been deleted, 0 represents it has not been deleted, the deleted rules will not be retrieved when using the interface for querying rules
        type: integer
      enabled:
        description: Enable&Disable 1 Enable, 0 Disable
        type: integer
      id:
        description: Rule id
        type: string
      metric:
        description: Monitoring item
        type: string
      metricName:
        description: Name of rule id monitoring item
        type: string
      noticePeriod:
        description: Notification period unit: hour
        type: integer
      noticeTime:
        description: Alarm time
        type: string
        format: date-time
      operation:
        description: '>=、>、<、<=、==、！='
        type: string
      period:
        description: Statistical period (unit: minute)
        type: integer
      region:
        description: Region information
        type: string
      resourceId:
        description: Resource id applied by this rule
        type: string
      serviceCode:
        description: Product corresponded to the alarm rule
        type: string
      tag:
        description: Auxiliary information of monitoring item
        type: string
      threshold:
        description: Threshold
        type: number
        format: double
      times:
        description: Alarm after how many times
        type: integer
      value:
        description: Alarm value
        type: number
        format: double
  
  alarm:
    ###################### Alarm information######################  
    x-jdcloud-module: monitor
    type: object
    properties:
      calculation:
        description: Statistical method: average value=avg, maximum value=max, minimum value=min,
        type: string
      contactGroups:
        description: Contact group notified, for example [“contact group 1”, “contact group 2”]
        type: array
        items:
          type: string
      contactPersons:
        description: Contact notified, for example“[‘contact 1’, ‘contact 2’]”
        type: array
        items:
          type: string
      createTime:
        description: Creation time
        type: string
        format: date-time
      enabled:
        description: Enable&Disable 1 Enable, 0 Disable
        type: integer
      id:
        description: Rule id
        type: string
      metric:
        description: Monitoring item
        type: string
      metricName:
        description: Name of rule id monitoring item
        type: string
      noticePeriod:
        description: Notification period unit: hour
        type: integer
      noticeTime:
        description: Alarm time  ,  this field is valid when querying the alarming rule
        type: string
        format: date-time
      operation:
        description: '>=、>、<、<=、==、！='
        type: string
      period:
        description: Statistical period (unit: minute)
        type: integer
      region:
        description: Region information
        type: string
      resourceId:
        description: Resource id applied by this rule
        type: string
      serviceCode:
        description: Product corresponded to the alarm rule
        type: string
      status:
        description: Monitoring item status: 1 Normal, 2 Alarm, 4 Insufficient data
        type: integer
      tag:
        description: Auxiliary information of monitoring item
        type: string
      threshold:
        description: Threshold
        type: number
        format: double
      times:
        description: Alarm after how many times
        type: integer
      value:
        description: Alarm value, this field is valid when querying the alarming rule
        type: number
        format: double
