swagger: "2.0"
definitions:
  instanceNetworkInterface:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: Describe instance’s network interface information
    properties:
      networkInterfaceId:
        type: string
        description: Elastic network interface ID
      macAddress:
        type: string
        description: Ethernet address
      vpcId:
        type: string
        description: Virtual network ID
      description:
        type: string
        description: Description
      securityGroups:
        type: array
        items:
          $ref: "./SecurityGroupSimple.yaml#/definitions/securityGroupSimple"
        description: Security group list
      sanityCheck:
        type: boolean
        description: Source and target IP address verification, with value 0 or 1
      primaryIp:
        $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: Primary IP of network interface
      secondaryIps:
        type: array
        items:
          $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: 