swagger: "2.0"
info:
  description: Monitoring Items APIs, providing functions such as available monitoring item list query and monitoring data query
  title: Monitoring Items APIs
  version: "v1"
consumes:
- application/json
produces:
- application/json

paths:
  /metrics:
    ###################### Query available monitoring item list based on the product line ######################    
    get:
      description: Query indicator list available to get monitoring data based on resource type
      summary: Query available monitoring item list based on the product line
      operationId: describeMetrics
      x-jdcloud-internal: false
      parameters:
      - type: string
        description: |
          Type of resource: 
          vm--> virtual machine
          disk-->cloud disk
          ip--> public IP
          balance-->load balancer
          database-->MySQL Service revision
          cdn-->JD CDN
          redis-->redis cloud cache
          mongodb-->mongoDB cloud cache
          storage-->cloud storage
          sqlserver-->cloud database sqlserver revision 
          nativecontainer-->container
        name: serviceCode
        in: query
        required: true
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: Requested identifier id
              result:
                properties:
                  metrics:
                    type: array
                    items:
                      $ref: '../model/MetricDatail.yaml#/definitions/metricDetail'
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"

  /metricsForCreateAlarm:
    get:
      description: Query indicator list available to create monitoring rules based on resource type
      summary: Query indicator list of available creating monitoring rules
      operationId: describeMetricsForCreateAlarm
      x-jdcloud-internal: false      
      parameters:
      - type: string
        description: |
          Type of resource, blank by default, displaying all items
          vm--> virtual machine
          disk-->cloud disk
          ip--> public IP
          balance-->load balancer
          database-->MySQL Service revision
          cdn-->JD CDN
          redis-->redis cloud cache
          mongodb-->mongoDB cloud cache
          storage-->cloud storage
          sqlserver-->cloud database sqlserver revision 
          nativecontainer-->container
        name: serviceCode
        in: query
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: Requested identifier id
              result:
                properties:
                  serviceCodeList:
                    type: array
                    items:
                      $ref: '../model/MetricDatail.yaml#/definitions/ServiceCodeMetrics'
        400:
          description: 'invalid parameter'
        500:
          description: 'internal server error'
          
  /regions/{regionId}/metrics/{metric}/metricData:
    ######################View monitoring data of certain resource ######################  
    get:
      description: View certain resource monitoring data, which needs to designate the monitoring indicator and the time range.
      summary: View monitoring data of certain resource
      operationId: describeMetricData
      x-jdcloud-internal: false      
      parameters:
      - type: string
        description: Region Id
        name: regionId
        in: path
        required: true
      - type: string
        description: English identifier (id) of monitoring item
        name: metric
        in: path
        required: true
      - type: string
        description: Type of resource, taking values such as vm, lb, ip, database
        name: serviceCode
        in: query
        required: true
      - type: string
        description: uuid of resource
        name: resourceId
        in: query
        required: true
      - type: string
        description: Query start time of time range, UTC time, format: yyyy-MM-dd'T’HH:mm:ssZ (current time by default, if it is earlier than 30d, it will be reset to 30d)
        name: startTime
        in: query
      - type: string
        description: Query end time of time range, UTC time, format: 2016-12- yyyy-MM-dd'T’HH:mm:ssZ (if it is blank, which shall be obtained by computing startTime and timeInterval)
        name: endTime
        in: query
      - type: string
        description: Time interval: 1h, 6h, 12h, 1d, 3d, 7d, 14d, fixed time interval, fill in at least one of timeInterval and endTime
        name: timeInterval
        in: query
      - name: tags
        in: query
        type: array
        items:
          $ref: "../model/Tags.yaml#/definitions/tagFilter"
        description: Customized tag
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: Requested identifier id
              result:
                properties:
                  metricDatas:
                    type: array
                    items:
                      $ref: '../model/MetricData.yaml#/definitions/metricData'
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
  /regions/{regionId}/metrics/{metric}/lastDownsample:
    get:
      description: View the last point at certain resource
      summary: View the last point at certain resource
      operationId: lastDownsample
      x-jdcloud-internal: true      
      parameters:
      - type: string
        description: Region Id
        name: regionId
        in: path
        required: true
      - type: string
        description: English identifier (id) of monitoring item
        name: metric
        in: path
        required: true
      - type: string
        description: Type of resource, taking values such as vm, lb, ip, database
        name: serviceCode
        in: query
        required: true
      - type: string
        description: uuid of resource
        name: resourceId
        in: query
        required: true
      - name: tags
        in: query
        type: array
        description: Customized tag
        items:
          $ref: "../model/Tags.yaml#/definitions/tagFilter"
      - type: string
        description: Query start time of time range, UTC time, format: yyyy-MM-dd'T’HH:mm:ssZ (current time by default, if it is earlier than 30d, it will be reset to 30d)
        name: startTime
        in: query
      - type: string
        description: Query end time of time range, UTC time, format: 2016-12- yyyy-MM-dd'T’HH:mm:ssZ (if it is blank, which shall be obtained by computing startTime and timeInterval)
        name: endTime
        in: query
      - type: string
        description: Queried time interval, only supporting the minute-level, for example: 1m
        name: timeInterval
        in: query
      - type: string
        description: Aggregation method: max avg min and so on
        name: aggrType
        in: query
      responses:
        200:
          description: View the last point at certain resource
          schema:
            type: object
            required:
            - requestId
            properties:
              requestId:
                description: Requested identifier id
                type: string
              result:
                properties:
                  items:
                    type: array
                    items:
                      $ref: '../model/LastDownsampleRespItem.yaml#/definitions/lastDownsampleRespItem'
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
