swagger: "2.0"
info:
  version: "v1"
  title: Specification Type
  description: interface related to specifications type operation

basePath: /regions/{regionId}

paths:
  "/instanceTypes":
    ###################### Specification List Interface ######################
    get:
      description: |
        Query specification type information list
      operationId: describeInstanceTypes
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            instanceTypes-specification type,  exact match,  multiple support
            az-Availability zone,  exact match,  multiple support
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  instanceTypes:
                    description: Generic specification type
                    type: array
                    items:
                      $ref: "../model/InstanceType.yaml#/definitions/instanceType"
                  specificInstanceTypes:
                    description: user-specific type of specification; Work Order Request Required
                    type: array
                    items:
                      $ref: "../model/InstanceType.yaml#/definitions/instanceType"
                  totalCount:
                    type: integer
                    description: quantity
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# path general parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Geo ID
