swagger: "2.0"
definitions:
  instanceTypeState:
    x-jdcloud-module: vm
    properties:
      az:
        type: string
        description: availability zone
      inStock:
        type: boolean
        Description:tradable situation,  true: available,  false: sold,  unavailable
